name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  swap-test:
    name: Swap (Task 1)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3

      - name: Build
        working-directory: os/lab02/01_swap
        run: make

      - name: Test
        working-directory: os/lab02/01_swap
        run: python3 -m unittest discover -v tests

  array-reverse-test:
    name: Array Reverse (Task 2)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3

      - name: Build
        working-directory: os/lab02/02_array_reverse
        run: make

      - name: Test
        working-directory: os/lab02/02_array_reverse
        run: python3 -m unittest discover -v tests

  matrix-transpose-test:
    name: Matrix Transpose (Task 3)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3

      - name: Build
        working-directory: os/lab02/03_matrix_transpose
        run: make

      - name: Test
        working-directory: os/lab02/03_matrix_transpose
        run: python3 -m unittest discover -v tests

  list-reverse-test:
    name: List Reverse (Task 4)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3

      - name: Build
        working-directory: os/lab02/04_list_reverse
        run: make

      - name: Test
        working-directory: os/lab02/04_list_reverse
        run: python3 -m unittest discover -v tests

  second-assignment:
    name: SecondAssignment (Interposition)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc python3

      - name: Build
        working-directory: os/lab04/01_interposition
        run: make

      - name: Test
        working-directory: os/lab04/01_interposition
        run: python3 -m unittest discover -v tests