name: FirstAssignment

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task-folder:
          - os/lab02/01_swap
          - os/lab02/02_array_reverse
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3

      - name: Build ${{ matrix.task-folder }}
        working-directory: ${{ matrix.task-folder }}
        run: make

      - name: Test ${{ matrix.task-folder }}
        working-directory: ${{ matrix.task-folder }}
        run: python3 -m unittest discover -v tests